### ISSUE TITLE
[2주차] 웹 어댑터 구현하기

### ISSUE THREAD

**Issue by sirzzang** [sirzzang/hexagonal-coupon-service#3]
# 웹 어댑터 구현하기

* 웹 어댑터: 어플리케이션이 웹(*외부 세계*)과 커뮤니케이션할 때 거쳐야 하는 계층
    - 어플리케이션을 호출하는(으로 향하는) 인커밍 어댑터
    - 의존성 역전(p.54): 제어 흐름을 역전시켜, 서비스 및 웹 어댑터가 의존하는 추상화된 인터페이스(포트) 계층을 둠
        - 인커밍 웹 어댑터는 포트를 호출
        - 어플리케이션 서비스는 포트를 구현
   
* 두 가지 역할을 하는 어댑터 시나리오(p.55)
  - 인커밍 웹 어댑터가 두 가지 역할을 할 수도 있음: 웹소켓 컨트롤러
  - 의존성 역전
      - 인커밍 포트 호출: 브라우저에서 사용자 데이터를 어플리케이션으로 전달하기 위해 서비스 호출
      - 아웃고잉 포트의 구현: 사용자 데이터를 브라우저로 전달하는 것을 구현

* 웹 어댑터의 책임
  - **HTTP 요청을 자바 객체로 매핑**: 컨트롤러 리소스(p.61)
  - _권한 검사_
  - _입력 유효성 검증_
  - **입력을 유스케이스의 입력 모델로 매핑**: 컨트롤러 리소스를 서비스 커맨드로 생성
  - **유스케이스 호출**
  - **유스케이스의 출력을 HTTP로 매핑**
  - **HTTP 응답을 반환**

* 컨트롤러의 구성
  - 웹 어댑터를 한 개 이상의 컨트롤러로 구성
  - 가능한 한 좁고, 많은 컨트롤러를 만들 것

# 결론

웹 어댑터의 구현을 통해, 

  - 웹 어댑터는 어떠한 도메인 로직도 수행하지 않음
  - 어플리케이션 계층도 HTTP와 관련된 어떠한 작업도 하지 않음

으로써 유지보수성을 향상시킬 수 있다

<br>

# TODO

- [x] 책에서는 유스케이스별로 웹 어댑터 컨트롤러 계층 나눠 작성했는데, 그렇게 해야 하는 건가
    - 유스케이스를 너무 많이 쪼개면 어떻게 되는거지?
- [ ] 1주차 논의사항 바탕으로 패키지 구조 변경했는데, 옳은 방향일지 고민해 보기
- [x] 컨트롤러에서 바로 도메인을 불러도 될까 → 컨트롤러의 입력 모델 필요
- [x] 컨트롤러의 입력 모델에 대한 해석: `DTO` vs. Inner Class → Inner Class
- [x] 접근제어자 레벨 수정
- [x] 샵 생성, 수정 시 샵 객체를 전부 반환할 필요가 있을지?
- [ ] 생성자로 생성 시, 샵 수정해야 할 때 어떻게 하는 게 best일까
- [ ] 도메인에서 `newShop`, `existingShop` 메서드를 사용하는 게 책의 내용과 맞는 방향인가. 이게 도메인 로직이라고 볼 수 있는가

**Comment by sirzzang** [comment]
컨트롤러 자체의 모델 -> `private`으로 컨트롤러 안에?
